org.gradle.jvmargs=-Xmx2G -Djava.io.tmpdir=.gradle-tmp
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.16.5
yarn_mappings=1.16.5+build.10
loader_version=0.16.14
fabric_api_version=0.42.0+1.16
loom_version=1.17.17

mod_version=1.0
maven_group=com.andresblue
archives_base_name=tristorage-mc1.16.5
